spring:
  application:
    name: panggilan-loket

queue:
  counters:
    - id: A
      name: Loket A
    - id: B
      name: Loket B
    - id: C
      name: Loket C

printer:
  ticket:
    enabled: true
    institution-name: "RS CAHAYA MEDIKA"
    address: "jl. Gajah Mada, Kel. Leneng, Praya, Loteng"
